apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: todo-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongo  # يمكن تغييره إلى مسار آخر على الـ Node

